version: "3.5"

services:
    taiga-db:
        image: postgres:13
        container_name: taiga-db
        restart: always
        environment:
            POSTGRES_DB: taiga
            POSTGRES_USER: taiga
            POSTGRES_PASSWORD: taiga_password
        volumes:
            - taiga-db-data:/var/lib/postgresql/data
        networks:
            - taiga

    taiga-backend:
        image: elestio/taiga-backend:latest
        container_name: taiga-backend
        restart: always
        environment:
            POSTGRES_DB: taiga
            POSTGRES_USER: taiga
            POSTGRES_PASSWORD: taiga_password
            POSTGRES_HOST: taiga-db
            TAIGA_SECRET_KEY: taiga_secret_key
            TAIGA_SITES_SCHEME: "https"
            TAIGA_SITES_DOMAIN: taiga.awpsoft.com.br
            EVENTS_PUSH_BACKEND: "taiga.events.backends.rabbitmq"
            EVENTS_PUSH_BACKEND_URL: "amqp://taiga:taiga_password@taiga-rabbitmq:5672/"
            PUBLIC_REGISTER_ENABLED: "True"
        volumes:
            - taiga-static-data:/taiga-back/static
            - taiga-media-data:/taiga-back/media
        depends_on:
            - taiga-db
            - taiga-rabbitmq
        networks:
            - taiga
        ports:
            - "8000:8000"

    taiga-frontend:
        image: elestio/taiga-frontend:latest
        container_name: taiga-frontend
        restart: always
        environment:
            TAIGA_URL: "https://taiga.awpsoft.com.br"
            TAIGA_WEBSOCKETS_URL: "wss://taiga.awpsoft.com.br"
            PUBLIC_REGISTER_ENABLED: "true"
        networks:
            - taiga
        depends_on:
            - taiga-backend
        ports:
            - "9000:80"

    taiga-rabbitmq:
        image: rabbitmq:3-management
        container_name: taiga-rabbitmq
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: taiga
            RABBITMQ_DEFAULT_PASS: taiga_password
        networks:
            - taiga

volumes:
    taiga-db-data:
    taiga-static-data:
    taiga-media-data:

networks:
    taiga: