version: "3.5"

services:
    taiga-db:
        image: postgres:13
        container_name: taiga-db
        restart: always
        environment:
            POSTGRES_DB: taiga
            POSTGRES_USER: taiga
            POSTGRES_PASSWORD: "Taiga750*"
        volumes:
            - ./taiga-db-data:/var/lib/postgresql/data
        networks:
            - taiga
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U taiga"]
            interval: 30s
            timeout: 10s
            retries: 5

    taiga-backend:
        image: elestio/taiga-backend:latest
        container_name: taiga-backend
        restart: always
        environment:
            POSTGRES_DB: taiga
            POSTGRES_USER: taiga
            POSTGRES_PASSWORD: "Taiga750*"
            POSTGRES_HOST: taiga-db
            TAIGA_SECRET_KEY: "Taiga750*"
            TAIGA_SITES_SCHEME: "http"
            TAIGA_SITES_DOMAIN: "localhost"
            PUBLIC_REGISTER_ENABLED: "True"
        volumes:
            - ./taiga-static-data:/taiga-back/static
            - ./taiga-media-data:/taiga-back/media
        depends_on:
            taiga-db:
                condition: service_healthy
        networks:
            - taiga
        ports:
            - "8000:8000"

    taiga-frontend:
        image: elestio/taiga-frontend:latest
        container_name: taiga-frontend
        restart: always
        environment:
            TAIGA_URL: "http://localhost:8000"
            PUBLIC_REGISTER_ENABLED: "true"
        networks:
            - taiga
        depends_on:
            - taiga-backend
        ports:
            - "9000:80"

networks:
    taiga: